version: "3.3"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
            BUILD_ENV: local
    container_name: dashboard
    ports:
      - "3000:3000"
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080