ARG VERSION=14.13.1
ARG PORT=3000

FROM node:${VERSION}-slim
RUN npm i -g serve
RUN apt-get update && apt-get install -y \
  curl 

ARG API_URL
ARG API_KEY
ARG AUTH_DOMAIN
ARG DATABASE_URL
ARG PROJECT_ID
ARG MESSAGING_SENDER_ID
ARG APP_ID
ARG MEASUREMENT_ID
ARG STORAGE_BUCKET 

ARG BUILD_ARG=development 
ENV BUILD_ENV=$BUILD_ARG



RUN  echo $BUILD_ENV

WORKDIR /app
COPY  . /app
RUN export NODE_OPTIONS=--max_old_space_size=12288
RUN npm i

RUN REACT_APP_API_URL=$API_URL \
  REACT_APP_API_KEY=$API_KEY \
  REACT_APP_AUTH_DOMAIN=$AUTH_DOMAIN \
  REACT_APP_DATABASE_URL=$DATABASE_URL \
  REACT_APP_PROJECT_ID=$PROJECT_ID \
  REACT_APP_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID \
  REACT_APP_APP_ID=$APP_ID \
  REACT_APP_MEASUREMENT_ID=$MEASUREMENT_ID \
  REACT_APP_STORAGE_BUCKET=$STORAGE_BUCKET npm run build:$BUILD_ENV

HEALTHCHECK --interval=5s --timeout=2s --retries=12 \
  CMD curl --silent --fail localhost:${PORT} || exit 1

EXPOSE ${PORT}
CMD ["serve","-s", "build", "-l", "3000"]
